apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ybiz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ybiz
    app.kubernetes.io/part-of: byoc-app-kajp
  name: ybiz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ybiz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ybiz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-uxwa-tenant/byoc-app-kajp/ybiz@sha256:1b3ff0b72a56fcd36628814a8fa2af3b10371c1221466d8cf6cd6f75812b3589
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
