apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ybiz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ybiz
    app.kubernetes.io/part-of: byoc-app-kajp
  name: ybizcztw
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: ybiz
    weight: null
status: {}
